//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace k22cntt3pvv2210900085.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class pvv2210900085Entities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new pvv2210900085Entities object using the connection string found in the 'pvv2210900085Entities' section of the application configuration file.
        /// </summary>
        public pvv2210900085Entities() : base("name=pvv2210900085Entities", "pvv2210900085Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new pvv2210900085Entities object.
        /// </summary>
        public pvv2210900085Entities(string connectionString) : base(connectionString, "pvv2210900085Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new pvv2210900085Entities object.
        /// </summary>
        public pvv2210900085Entities(EntityConnection connection) : base(connection, "pvv2210900085Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PvvCategory> PvvCategory
        {
            get
            {
                if ((_PvvCategory == null))
                {
                    _PvvCategory = base.CreateObjectSet<PvvCategory>("PvvCategory");
                }
                return _PvvCategory;
            }
        }
        private ObjectSet<PvvCategory> _PvvCategory;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PvvProduct> PvvProduct
        {
            get
            {
                if ((_PvvProduct == null))
                {
                    _PvvProduct = base.CreateObjectSet<PvvProduct>("PvvProduct");
                }
                return _PvvProduct;
            }
        }
        private ObjectSet<PvvProduct> _PvvProduct;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<sysdiagrams> sysdiagrams
        {
            get
            {
                if ((_sysdiagrams == null))
                {
                    _sysdiagrams = base.CreateObjectSet<sysdiagrams>("sysdiagrams");
                }
                return _sysdiagrams;
            }
        }
        private ObjectSet<sysdiagrams> _sysdiagrams;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PvvCategory EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPvvCategory(PvvCategory pvvCategory)
        {
            base.AddObject("PvvCategory", pvvCategory);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PvvProduct EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPvvProduct(PvvProduct pvvProduct)
        {
            base.AddObject("PvvProduct", pvvProduct);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the sysdiagrams EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosysdiagrams(sysdiagrams sysdiagrams)
        {
            base.AddObject("sysdiagrams", sysdiagrams);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="pvv2210900085Model", Name="PvvCategory")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PvvCategory : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PvvCategory object.
        /// </summary>
        /// <param name="nbtID">Initial value of the nbtID property.</param>
        public static PvvCategory CreatePvvCategory(global::System.Int32 nbtID)
        {
            PvvCategory pvvCategory = new PvvCategory();
            pvvCategory.nbtID = nbtID;
            return pvvCategory;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 nbtID
        {
            get
            {
                return _nbtID;
            }
            set
            {
                if (_nbtID != value)
                {
                    OnnbtIDChanging(value);
                    ReportPropertyChanging("nbtID");
                    _nbtID = StructuralObject.SetValidValue(value, "nbtID");
                    ReportPropertyChanged("nbtID");
                    OnnbtIDChanged();
                }
            }
        }
        private global::System.Int32 _nbtID;
        partial void OnnbtIDChanging(global::System.Int32 value);
        partial void OnnbtIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String nbtCateName
        {
            get
            {
                return _nbtCateName;
            }
            set
            {
                OnnbtCateNameChanging(value);
                ReportPropertyChanging("nbtCateName");
                _nbtCateName = StructuralObject.SetValidValue(value, true, "nbtCateName");
                ReportPropertyChanged("nbtCateName");
                OnnbtCateNameChanged();
            }
        }
        private global::System.String _nbtCateName;
        partial void OnnbtCateNameChanging(global::System.String value);
        partial void OnnbtCateNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> nbtStatus
        {
            get
            {
                return _nbtStatus;
            }
            set
            {
                OnnbtStatusChanging(value);
                ReportPropertyChanging("nbtStatus");
                _nbtStatus = StructuralObject.SetValidValue(value, "nbtStatus");
                ReportPropertyChanged("nbtStatus");
                OnnbtStatusChanged();
            }
        }
        private Nullable<global::System.Boolean> _nbtStatus;
        partial void OnnbtStatusChanging(Nullable<global::System.Boolean> value);
        partial void OnnbtStatusChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="pvv2210900085Model", Name="PvvProduct")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PvvProduct : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PvvProduct object.
        /// </summary>
        /// <param name="nbt2210900140">Initial value of the nbt2210900140 property.</param>
        /// <param name="property1">Initial value of the Property1 property.</param>
        public static PvvProduct CreatePvvProduct(global::System.String nbt2210900140, global::System.String property1)
        {
            PvvProduct pvvProduct = new PvvProduct();
            pvvProduct.nbt2210900140 = nbt2210900140;
            pvvProduct.Property1 = property1;
            return pvvProduct;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nbt2210900140
        {
            get
            {
                return _nbt2210900140;
            }
            set
            {
                if (_nbt2210900140 != value)
                {
                    Onnbt2210900140Changing(value);
                    ReportPropertyChanging("nbt2210900140");
                    _nbt2210900140 = StructuralObject.SetValidValue(value, false, "nbt2210900140");
                    ReportPropertyChanged("nbt2210900140");
                    Onnbt2210900140Changed();
                }
            }
        }
        private global::System.String _nbt2210900140;
        partial void Onnbt2210900140Changing(global::System.String value);
        partial void Onnbt2210900140Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String nbtProName
        {
            get
            {
                return _nbtProName;
            }
            set
            {
                OnnbtProNameChanging(value);
                ReportPropertyChanging("nbtProName");
                _nbtProName = StructuralObject.SetValidValue(value, true, "nbtProName");
                ReportPropertyChanged("nbtProName");
                OnnbtProNameChanged();
            }
        }
        private global::System.String _nbtProName;
        partial void OnnbtProNameChanging(global::System.String value);
        partial void OnnbtProNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> nbtQty
        {
            get
            {
                return _nbtQty;
            }
            set
            {
                OnnbtQtyChanging(value);
                ReportPropertyChanging("nbtQty");
                _nbtQty = StructuralObject.SetValidValue(value, "nbtQty");
                ReportPropertyChanged("nbtQty");
                OnnbtQtyChanged();
            }
        }
        private Nullable<global::System.Int32> _nbtQty;
        partial void OnnbtQtyChanging(Nullable<global::System.Int32> value);
        partial void OnnbtQtyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> nbtPrice
        {
            get
            {
                return _nbtPrice;
            }
            set
            {
                OnnbtPriceChanging(value);
                ReportPropertyChanging("nbtPrice");
                _nbtPrice = StructuralObject.SetValidValue(value, "nbtPrice");
                ReportPropertyChanged("nbtPrice");
                OnnbtPriceChanged();
            }
        }
        private Nullable<global::System.Double> _nbtPrice;
        partial void OnnbtPriceChanging(Nullable<global::System.Double> value);
        partial void OnnbtPriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> nbtCateId
        {
            get
            {
                return _nbtCateId;
            }
            set
            {
                OnnbtCateIdChanging(value);
                ReportPropertyChanging("nbtCateId");
                _nbtCateId = StructuralObject.SetValidValue(value, "nbtCateId");
                ReportPropertyChanged("nbtCateId");
                OnnbtCateIdChanged();
            }
        }
        private Nullable<global::System.Int32> _nbtCateId;
        partial void OnnbtCateIdChanging(Nullable<global::System.Int32> value);
        partial void OnnbtCateIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> nbtActive
        {
            get
            {
                return _nbtActive;
            }
            set
            {
                OnnbtActiveChanging(value);
                ReportPropertyChanging("nbtActive");
                _nbtActive = StructuralObject.SetValidValue(value, "nbtActive");
                ReportPropertyChanged("nbtActive");
                OnnbtActiveChanged();
            }
        }
        private Nullable<global::System.Boolean> _nbtActive;
        partial void OnnbtActiveChanging(Nullable<global::System.Boolean> value);
        partial void OnnbtActiveChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Property1
        {
            get
            {
                return _Property1;
            }
            set
            {
                OnProperty1Changing(value);
                ReportPropertyChanging("Property1");
                _Property1 = StructuralObject.SetValidValue(value, false, "Property1");
                ReportPropertyChanged("Property1");
                OnProperty1Changed();
            }
        }
        private global::System.String _Property1;
        partial void OnProperty1Changing(global::System.String value);
        partial void OnProperty1Changed();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="pvv2210900085Model", Name="sysdiagrams")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sysdiagrams : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new sysdiagrams object.
        /// </summary>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="principal_id">Initial value of the principal_id property.</param>
        /// <param name="diagram_id">Initial value of the diagram_id property.</param>
        public static sysdiagrams Createsysdiagrams(global::System.String name, global::System.Int32 principal_id, global::System.Int32 diagram_id)
        {
            sysdiagrams sysdiagrams = new sysdiagrams();
            sysdiagrams.name = name;
            sysdiagrams.principal_id = principal_id;
            sysdiagrams.diagram_id = diagram_id;
            return sysdiagrams;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false, "name");
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 principal_id
        {
            get
            {
                return _principal_id;
            }
            set
            {
                Onprincipal_idChanging(value);
                ReportPropertyChanging("principal_id");
                _principal_id = StructuralObject.SetValidValue(value, "principal_id");
                ReportPropertyChanged("principal_id");
                Onprincipal_idChanged();
            }
        }
        private global::System.Int32 _principal_id;
        partial void Onprincipal_idChanging(global::System.Int32 value);
        partial void Onprincipal_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 diagram_id
        {
            get
            {
                return _diagram_id;
            }
            set
            {
                if (_diagram_id != value)
                {
                    Ondiagram_idChanging(value);
                    ReportPropertyChanging("diagram_id");
                    _diagram_id = StructuralObject.SetValidValue(value, "diagram_id");
                    ReportPropertyChanged("diagram_id");
                    Ondiagram_idChanged();
                }
            }
        }
        private global::System.Int32 _diagram_id;
        partial void Ondiagram_idChanging(global::System.Int32 value);
        partial void Ondiagram_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> version
        {
            get
            {
                return _version;
            }
            set
            {
                OnversionChanging(value);
                ReportPropertyChanging("version");
                _version = StructuralObject.SetValidValue(value, "version");
                ReportPropertyChanged("version");
                OnversionChanged();
            }
        }
        private Nullable<global::System.Int32> _version;
        partial void OnversionChanging(Nullable<global::System.Int32> value);
        partial void OnversionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] definition
        {
            get
            {
                return StructuralObject.GetValidValue(_definition);
            }
            set
            {
                OndefinitionChanging(value);
                ReportPropertyChanging("definition");
                _definition = StructuralObject.SetValidValue(value, true, "definition");
                ReportPropertyChanged("definition");
                OndefinitionChanged();
            }
        }
        private global::System.Byte[] _definition;
        partial void OndefinitionChanging(global::System.Byte[] value);
        partial void OndefinitionChanged();

        #endregion

    }

    #endregion

}
